// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { prismaCliUrl } from "./src/prisma/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DATABASE_URL is libpq-style; translate it so migrations verify TLS too.
    url: prismaCliUrl(process.env["DATABASE_URL"]),
  },
});
